dns_format: ${EnvironmentName}.${DnsDomain}

enabled: true
comment: ${EnvironmentName} distribution
export_name: cloudfront
# default_root_object: index.html

http_version: http2 # http1.1|http2
# ipv6: false

# custom_error_responses:
#   -
#     ErrorCachingMinTTL: 0
#     ErrorCode: 404
#     ResponseCode: 200
#     ResponsePagePath: /index.html

# origins:
#   loadbalancer:
#     source: loadbalancer
#     protocol_policy: https-only
#     custom_headers:
#         - HeaderName: x-test-header
#           HeaderValue: desiredvalue

ssl:
  type: cloudfront # acm|cloudfront|iam
  support_method: sni-only # sni-only|vip
  minimum_protocol_version: TLSv1.2_2018 # SSLv3|TLSv1|TLSv1_2016|TLSv1.1_2016|TLSv1.2_2018

behaviours:
  default:
    AllowedMethods:
      - GET
      - HEAD
    Compress: true
    TargetOriginId: s3bucket
    ForwardedValues:
      Cookies:
        Forward: none
      QueryString: true
    ViewerProtocolPolicy: redirect-to-https # allow-all|redirect-to-https|https-only
  # nondefaultcachebehaviours:
  #   -
  #     AllowedMethods:
  #       - GET
  #       - HEAD
  #       - OPTIONS
  #     Compress: true
  #     TargetOriginId: s3bucket
  #     ForwardedValues:
  #       Cookies:
  #         Forward: none
  #       QueryString: false
  #     ViewerProtocolPolicy: redirect-to-https
  #     PathPattern: /index.html

# dns_records:
#   - mycdn.${DnsDomain}

# logs:
#   bucket: mybucket.com
#   prefix: mysite

# geo_restrictions:
#   locations: 
#     - Antarctica
#     - etcetera
#   type: whitelist | blacklist | none